"""Application-specific texture optimisation (handoff Step 4).

Re-runs the riblet physics at each application's actual flow conditions and
fluid, then recommends the spacing that holds s+ inside the 10-20 band at
cruise. The drag model is unchanged - only the fluid, the body scale, and the
speed range differ from the study's plate case.

Cases (handoff section 4, Step 4):
  1. small UAV wing     - air, chord 0.30 m, cruise 15 m/s (friction-dominated)
  2. car roof panel     - air, length 1.50 m, 33 m/s highway (attached-flow zone)
  3. competitive swimwear - WATER, torso length 0.70 m, 2.0 m/s race pace

Usage:
    python applications.py            # writes applications/ tables + report
"""
import os

import numpy as np
import pandas as pd

import texture_model as tm

RHO_WATER_25C = 997.0          # kg/m^3
MU_WATER_25C = 8.90e-04        # Pa.s
NU_WATER = MU_WATER_25C / RHO_WATER_25C

SHAPES = ["blade", "scalloped", "v-groove", "u-groove"]


def u_tau_general(u_inf, re):
    """E1-E2 evaluated at an arbitrary Reynolds number."""
    return float(u_inf * np.sqrt(tm.cf_schlichting(re) / 2.0))


def evaluate_riblet(shape, s_um, h_over_s, u_inf, nu, re):
    """Riblet DR with explicit fluid properties (same equations E5-E11)."""
    ut = u_tau_general(u_inf, re)
    h_um = s_um * h_over_s
    dr, sp_, lgp = tm.riblet_fr([shape], [s_um], [h_um], [ut])
    return float(dr[0]), float(sp_[0]), float(lgp[0]), ut


def sweep_case(name, body_note, u_inf, nu, characteristic_m, h_over_s,
               spacings_um, speeds):
    rows = []
    for u in speeds:
        re = u * characteristic_m / nu
        ut = u_tau_general(u, re)
        for s in spacings_um:
            for shape in SHAPES:
                dr, sp_, lgp, _ = evaluate_riblet(shape, s, h_over_s, u, nu, re)
                rows.append(dict(application=name, body=body_note,
                                 U_inf_mps=u, Re=re, u_tau_mps=round(ut, 5),
                                 shape=shape, spacing_um=s, h_over_s=h_over_s,
                                 s_plus=round(sp_, 3), lg_plus=round(lgp, 3),
                                 DR_friction_pct=round(dr, 3),
                                 in_band=bool(10.0 <= sp_ <= 20.0)))
    return pd.DataFrame(rows)


def recommend(case_df, cruise_speed):
    d = case_df[case_df.U_inf_mps == cruise_speed]
    best = d.loc[d.DR_friction_pct.idxmax()]
    # spacing whose s+ stays inside 10-20 across the whole speed envelope
    band = d.groupby(["shape", "spacing_um"]).in_band.all().reset_index()
    robust = band[band.in_band]
    return {
        "peak_at_cruise": {"shape": best["shape"], "spacing_um": float(best.spacing_um),
                           "DR_pct": float(best.DR_friction_pct),
                           "s_plus": float(best.s_plus)},
        "robust_in_band_choices": robust.to_dict("records"),
    }


CASES = [
    dict(name="uav_wing", label="Small UAV wing (air)",
         body_note="flat-plate analogy, friction-dominated",
         u_inf=15.0, nu=tm.NU, characteristic_m=0.30, h_over_s=0.5,
         spacings_um=[20, 30, 40, 50, 60, 80, 100, 150, 200],
         speeds=[8, 10, 12, 15, 18, 20]),
    dict(name="car_roof", label="Car roof attached-flow panel (air)",
         body_note="attached zone only; rear separation NOT modelled",
         u_inf=33.0, nu=tm.NU, characteristic_m=1.50, h_over_s=0.5,
         spacings_um=[50, 75, 100, 150, 200, 300, 400, 600],
         speeds=[15, 22, 27, 33, 38]),
    dict(name="swimwear", label="Competitive swimwear (WATER)",
         body_note="water; do not transfer air results directly",
         u_inf=2.0, nu=NU_WATER, characteristic_m=0.70, h_over_s=0.5,
         spacings_um=[10, 15, 20, 25, 30, 40, 50, 75, 100],
         speeds=[1.2, 1.5, 1.8, 2.0, 2.2]),
]


def main(outdir="applications"):
    os.makedirs(outdir, exist_ok=True)
    report = ["# Application-Specific Texture Optimisation",
              "",
              "Generated by `applications.py` (handoff Step 4). Riblet model "
              "unchanged; fluid, scale, and speed envelope per application.",
              "Positive DR = less skin-friction drag than a smooth surface at "
              "the same condition. Values are % of *friction* drag.",
              ""]
    for case in CASES:
        kw = {k: v for k, v in case.items() if k != "label"}
        df = sweep_case(**kw)
        path = os.path.join(outdir, f"{case['name']}_sweep.csv")
        df.to_csv(path, index=False)
        rec = recommend(df, case["u_inf"])
        cruise = df[df.U_inf_mps == case["u_inf"]]
        top5 = cruise.nlargest(5, "DR_friction_pct")
        report += [f"## {case['label']}",
                   f"- Cruise: {case['u_inf']} m/s, L = {case['characteristic_m']} m, "
                   f"nu = {case['nu']:.3e} m^2/s, Re_cruise = "
                   f"{case['u_inf'] * case['characteristic_m'] / case['nu']:.3e}",
                   f"- Peak at cruise: **{rec['peak_at_cruise']['shape']}** riblets, "
                   f"s = {rec['peak_at_cruise']['spacing_um']:.0f} um -> "
                   f"**{rec['peak_at_cruise']['DR_pct']:.2f} %** friction reduction "
                   f"(s+ = {rec['peak_at_cruise']['s_plus']:.1f})",
                   f"- Spacings holding s+=10-20 across the full envelope: "
                   f"{len(rec['robust_in_band_choices'])}",
                   "",
                   "| shape | s (um) | s+ | DR (%) |",
                   "|---|---|---|---|"]
        for _, r in top5.iterrows():
            sh = r["shape"]
            report.append(f"| {sh} | {r.spacing_um:.0f} | {r.s_plus:.1f} "
                          f"| {r.DR_friction_pct:.2f} |")
        report += ["", f"Full sweep: `{path}`", ""]
    with open(os.path.join(outdir, "APPLICATIONS.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(report))
    print("\n".join(report[:14]))
    print(f"... wrote {outdir}/APPLICATIONS.md")


if __name__ == "__main__":
    main()
